language: node_js
node_js:
  - node
install:
  - npm install -g firebase-tools polymer-cli
script:
  - polymer build --html.collapseWhitespace --insert-dependency-links
after_success:
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN --non-interactive
